# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='status',
            field=models.CharField(default='inactive', max_length=8),
        ),
    ]
