# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20180620_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='noti_time',
            field=models.DateTimeField(),
        ),
    ]
