# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20180620_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
