# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20180626_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='status',
            field=models.CharField(default='inactive', max_length=12),
        ),
    ]
