# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20180628_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='header',
            field=models.CharField(max_length=50),
        ),
    ]
