# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20180703_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='status',
        ),
    ]
