- name: Installs uWsgi
  apt: pkg=uwsgi state=installed update-cache=yes
  sudo: yes
  tags:
    - setup
    - uwsgi
    - prepare

- name: Install uwsgi python plugin
  apt: pkg=uwsgi-plugin-python state=installed update-cache=yes
  sudo: yes
  tags:
    - setup
    - uwsgi
    - prepare

- name: put uwsgi file in app-enabled
  template: src=attendant_uwsgi.ini.j2 dest=/etc/uwsgi/apps-enabled/attendant_uwsgi.ini
  sudo: yes
  tags:
    - setup
    - uwsgi
    - config
    - deploy
    - prepare

- name: restart uwsgi
  service: name=uwsgi state=restarted
  sudo: yes
  tags:
    - setup
    - uwsgi
    - deploy
    - restart
    - prepare
