- name: Installs uWsgi
  apt: pkg=uwsgi state=present update-cache=yes
  become: yes
  tags:
    - setup
    - uwsgi
    - prepare

- name: Install uwsgi python plugin
  apt: pkg=uwsgi-plugin-python state=present update-cache=yes
  become: yes
  tags:
    - setup
    - uwsgi
    - prepare

- name: put uwsgi file in app-enabled
  template: src=assignment_uwsgi.ini.j2 dest=/etc/uwsgi/apps-enabled/assignment_uwsgi.ini
  become: yes
  tags:
    - setup
    - uwsgi
    - config
    - deploy
    - prepare

- name: restart uwsgi
  service: name=uwsgi state=restarted
  become: yes
  tags:
    - setup
    - uwsgi
    - deploy
    - restart
    - prepare
