- name: create root project directory
  file: path=/srv/ owner='root' group='root' mode=0775 state=directory
  become: yes
  tags:
    - setup
    - webt
    - prepare

- name: changing ownership
  file: path={{ project_root }} owner='root' group='root' state=directory recurse=yes
  become: yes
  tags:
    - setup
    - webt
    - deploy


- name: deploy code from repository
  action: git accept_hostkey=yes repo={{ repo_url }} dest={{ project_root }}/{{ project_name }} remote={{ repo_remote }} version={{repo_branch}}
  become: yes
  force : yes
  tags:
    - setup
    - deploy
    - webt

- name: create root project directory
  file: path={{ project_root }} owner={{ deploy_user }} group={{ deploy_user }} state=directory recurse=yes
  become: yes
  tags:
    - setup
    - webt
    - deploy


- name: Fix for pip bug
  become: yes
  shell: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
  tags:
    - setup
    - deploy
    - webt


- name: install python dependencies
  become: yes
  action: pip requirements={{ project_root }}/{{project_name}}/requirements.txt
  tags:
    - setup
    - deploy
    - web

