- name: Install Nginx
  apt: pkg=nginx state=installed
  sudo: yes
  tags:
    - nginx


- name: Remove default Nginx site config
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes
  notify:
    - restart nginx
  tags:
    - nginx


- name: put nginx file in site-enabled
  template: src=assignment_nginx.conf.j2 dest=/etc/nginx/sites-enabled/accounts_nginx.conf
  sudo: yes
  notify:
    - restart nginx
  tags:
    - nginx